
enum class QueryType {
	AUTHORIZATION,
	REGISTRATION,
	CREATE_CHAT,
	UPDATE_MY_NAME,
	UPDATE_MY_PASSWORD,
	UPDATE_MY_PHOTO,
	LOAD_FRIEND_INFO,
	LOAD_ALL_FRIENDS_STATUSES,
	MESSAGE,
	MESSAGES_READ_CONFIRMATION,
	STATUS
};